### ISSUE TITLE
Sensor template formating

### ISSUE THREAD

**Issue by piotrbielaska** [PiotrMachowski/Home-Assistant-custom-components-MPK-KR#1]
Hi Piotr,

Did you, by any chance, created a template sensor based on this component? I'm trying to create one which will show me how many minutes I have to nearest tram going into particular direction. Based on what output I have from your sensor it would to be set of "for" and "if" loops looking for tram no. 9 going towards Mistrzejowice. Can you help me or at least point towards similar case already resolved for component outputting similar information?

**Comment by PiotrMachowski** [comment]
Hi, can you provide a state of you entity?

**Comment by piotrbielaska** [comment]
It is sensor.mpk_kr_kabel_tram_departure

**Comment by piotrbielaska** [comment]
I'm looking to output bold sub attribute value to separate template sensor.

State is: 
```
50, kier. Krowodrza Górka: 18:26 (0m)
```
Attributes:
```
stop_name: Kabel
list: 
- line: '50'
  direction: Krowodrza Górka
  departure: '18:27'
  original_departure: '18:25'
  time_to_departure: 0
  status: PREDICTED
- line: '50'
  direction: Kurdwanów P+R
  departure: '18:30'
  original_departure: '18:26'
  time_to_departure: 3
  status: PREDICTED
- line: '9'
  direction: Nowy Bieżanów P+R
  departure: '18:30'
  original_departure: '18:30'
  time_to_departure: 3
  status: PREDICTED
- line: '50'
  direction: Krowodrza Górka
  departure: '18:33'
  original_departure: '18:33'
  time_to_departure: 6
  status: PREDICTED
- line: '50'
  direction: Kurdwanów P+R
  departure: '18:36'
  original_departure: '18:33'
  time_to_departure: 9
  status: PREDICTED
- line: '9'
  direction: Mistrzejowice
  departure: '18:38'
  original_departure: '18:38'
  **time_to_departure: 11**
  status: PREDICTED
- line: '50'
  direction: Krowodrza Górka
  departure: '18:40'
  original_departure: '18:40'
  time_to_departure: 13
  status: PREDICTED
- line: '50'
  direction: Kurdwanów P+R
  departure: '18:42'
  original_departure: '18:41'
  time_to_departure: 15
  status: PREDICTED
- line: '9'
  direction: Nowy Bieżanów P+R
  departure: '18:45'
  original_departure: '18:45'
  time_to_departure: 18
  status: PREDICTED
- line: '50'
  direction: Krowodrza Górka
  departure: '18:47'
  original_departure: '18:47'
  time_to_departure: 20
  status: PREDICTED
- line: '50'
  direction: Kurdwanów P+R
  departure: '18:48'
  original_departure: '18:48'
  time_to_departure: 21
  status: PREDICTED

html_timetable: <table width="100%" border=1 style="border: 1px black solid; border-collapse: collapse;">
<tr><td style="text-align: center; padding: 4px"><big>50, kier. Krowodrza Górka</big></td><td style="text-align: right; padding: 4px">18:27, 18:33, 18:40, 18:47</td></tr>
<tr><td style="text-align: center; padding: 4px"><big>50, kier. Kurdwanów P+R</big></td><td style="text-align: right; padding: 4px">18:30, 18:36, 18:42, 18:48</td></tr>
<tr><td style="text-align: center; padding: 4px"><big>9, kier. Mistrzejowice</big></td><td style="text-align: right; padding: 4px">18:38</td></tr>
<tr><td style="text-align: center; padding: 4px"><big>9, kier. Nowy Bieżanów P+R</big></td><td style="text-align: right; padding: 4px">18:30, 18:45</td></tr>
</table>
html_departures: <table width="100%" border=1 style="border: 1px black solid; border-collapse: collapse;">
<tr><td style="text-align: center; padding: 4px">50, kier. Krowodrza Górka: 18:27 (0m)</td></tr>
<tr><td style="text-align: center; padding: 4px">50, kier. Kurdwanów P+R: 18:30 (3m)</td></tr>
<tr><td style="text-align: center; padding: 4px">9, kier. Nowy Bieżanów P+R: 18:30 (3m)</td></tr>
<tr><td style="text-align: center; padding: 4px">50, kier. Krowodrza Górka: 18:33 (6m)</td></tr>
<tr><td style="text-align: center; padding: 4px">50, kier. Kurdwanów P+R: 18:36 (9m)</td></tr>
<tr><td style="text-align: center; padding: 4px">9, kier. Mistrzejowice: 18:38 (11m)</td></tr>
<tr><td style="text-align: center; padding: 4px">50, kier. Krowodrza Górka: 18:40 (13m)</td></tr>
<tr><td style="text-align: center; padding: 4px">50, kier. Kurdwanów P+R: 18:42 (15m)</td></tr>
<tr><td style="text-align: center; padding: 4px">9, kier. Nowy Bieżanów P+R: 18:45 (18m)</td></tr>
<tr><td style="text-align: center; padding: 4px">50, kier. Krowodrza Górka: 18:47 (20m)</td></tr>
<tr><td style="text-align: center; padding: 4px">50, kier. Kurdwanów P+R: 18:48 (21m)</td></tr>
</table>
line: 50
direction: Krowodrza Górka
departure: 18:27
time_to_departure: 0
original_departure: 18:25
status: PREDICTED
friendly_name: MPK KR - Kabel departure
icon: mdi:bus-clock
```
