### ISSUE TITLE
Error parsing confi

### ISSUE THREAD

**Issue by KitHubek** [PiotrMachowski/Home-Assistant-custom-components-MPK-KR#2]
Hello

error in HA config.  What is wrong?

![fail](https://user-images.githubusercontent.com/91805313/164543781-3eeee59b-6e77-4e83-b003-5bd1aaae66fa.jpg)

```
  - platform: mpk_kr
      stops:
        - id: 119
          platform: bus
          mode: arrival
          directions:
            - "Starowiślna"
            - "Cracovia Stadion"
            - "Os. Podwawelskie"
            - "Prądnik Czerwony"
            - "Dworzec Główny Wschód"
            - "Złocień"
            - "Cichy Kącik"
        - id: 125
          platform: tram
          mode: arrival
          directions:
            - "Mały Płaszów P+R"
            - "Nowy Bieżanów P+R"
            - "Kurdwanów P+R"
```
