### ISSUE TITLE
Integration stopped to work 23:30 CET Yesterday

### ISSUE THREAD

**Issue by galandilias** [PiotrMachowski/Home-Assistant-custom-components-MPK-KR#3]
No more data is coming in - would you be able to check it out?

**Comment by PiotrMachowski** [comment]
Anything in logs?

**Comment by galandilias** [comment]
`WARNING (MainThread) [homeassistant.components.sensor] Updating mpk_kr sensor took longer than the scheduled update interval 0:00:30`

Only that one...

**Comment by PiotrMachowski** [comment]
Can you show your config?

**Comment by galandilias** [comment]
```yaml
sensor:
  - platform: mpk_kr
    stops:
      - id: 3040
        platform: tram
        mode: departure
        directions:
          - "Kurdwanów P+R"
          - "Bronowice Małe"
          - "Czerwone Maki P+R"
          - "Nowy Bieżanów P+R"
```

Rather standard.
